### ISSUE TITLE
Обновление модуля если в cc_manifest много данных

### ISSUE THREAD

**Issue by inthedark122** [essence-community/core-backend#356]
Как воспроизвести:

- создать модуль в котором в манифесте поместить документацию модуля с количеством символов больше 2000
- добавить модуль на платформу
- попробовать обновить архив модуля

При обновлении модуля увидим ошибку: `414 Request-URI Too Large`

Решение:

- Необходимо при обновлении модуля не отправлять cc_manifest, таким образом размер отпровляемых данных в query параметрам будет меньше

**Comment by toksy** [comment]
Исправлено в версии 2.6.4
