### ISSUE TITLE
При включенном кешировании страниц, меняется порядок объектов произвольным образом

### ISSUE THREAD

**Issue by toksy** [essence-community/core-backend#369]
Наткнулся на проблему, при включенном кешировании страниц в работе через докер 

при открытии страницы порядок объектов приходит в рандомном порядке 
(по метаданным структура страницы: 
Grid 
Panel
Panel 2) 

на фронте при этом строится в обратном порядке
Panel 2
Panel
Grid 

Помогает отключение кеширования и перезагрузка докера.

**Comment by Honyrik** [comment]
fix
